services:
  votes-app:
    build: .
    container_name: votes-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    environment:
      - TZ=Europe/Moscow
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs/fstbot.ru:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - votes-app
    networks:
      - app_network

  # Сервис для первоначального получения и автоматического обновления сертификатов
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./static:/var/www/certbot   # для проверки через веб-сервер
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;'"
    networks:
      - app_network
    depends_on:
      - nginx
    # Не запускаем автоматически, лучше выполнить вручную первый раз
    profiles:
      - certbot   # запускать только с --profile certbot, если нужен авторежим

networks:
  app_network:
    driver: bridge
